name: argo demo app

on:
    push:
        branches:
            - 'master'

jobs:
    build_and_push:
      name: build
      runs-on: ubuntu-latest
      steps: 
        - name: checkout
          uses: actions/checkout@v3
          
        - name: Setup go 1.19
          uses: actions/setup-go@v2
          with:
            go-version: '1.19.0'

        - name: vet application
          run: go vet

        - name: build executable
          run: go build app.go

        - name: authenticate with docker hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

        - name: extract metadata (tags, labels) for docker
          id: meta
          uses: docker/metadata-action@v4
          with:
              images: mannionjames/hello-argo
              tags: |
                type=sha

        - name: build and push
          uses: docker/build-push-action@v3
          with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
